import crafttweaker.api.item.IItemStack;
import crafttweaker.api.data.StringData;
import crafttweaker.api.data.ByteData;
import crafttweaker.api.data.IData;

mods.extendedcrafting.TableCrafting.addShaped("c15f7699-3009-4ea8-99ac-71e61bad60b7", 0, <item:extendedcrafting:the_ultimate_ingot>, [
	[<item:minecraft:copper_ingot>, <item:minecraft:iron_ingot>, <item:minecraft:gold_ingot>, <item:minecraft:netherite_ingot>, <item:aquaculture:neptunium_ingot>, <item:mysticalagriculture:prosperity_ingot>, <item:mysticalagriculture:soulium_ingot>, <item:mysticalagriculture:inferium_ingot>, <item:mysticalagriculture:prudentium_ingot>], 
	[<item:mysticalagriculture:tertium_ingot>, <item:mysticalagriculture:imperium_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:awakened_supremium_ingot>, <item:mysticalagradditions:insanium_ingot>, <item:naturesaura:infused_iron>, <item:naturesaura:tainted_gold>, <item:naturesaura:depth_ingot>, <item:naturesaura:sky_ingot>], 
	[<item:byg:pendorite_ingot>, <item:twilightforest:ironwood_ingot>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:fiery_ingot>, <tag:items:forge:ingots/lead>, <item:alltheores:osmium_ingot>, <tag:items:forge:ingots/platinum>, <tag:items:forge:ingots/silver>, <tag:items:forge:ingots/tin>], 
	[<tag:items:forge:ingots/uranium>, <tag:items:forge:ingots/steel>, <tag:items:forge:ingots/bronze>, <tag:items:forge:ingots/brass>, <item:blue_skies:falsite_ingot>, <item:blue_skies:ventium_ingot>, <item:blue_skies:horizonite_ingot>, <item:botania:manasteel_ingot>, <item:botania:terrasteel_ingot>], 
	[<item:botania:elementium_ingot>, <item:botania:gaia_ingot>, <item:ad_astra:desh_ingot>, <item:ad_astra:ostrum_ingot>, <item:ad_astra:calorite_ingot>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_redstone_ingot>, <item:extendedcrafting:ender_ingot>], 
	[<item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);

mods.extendedcrafting.TableCrafting.addShaped("b665fdc9-39bf-42c3-a337-ed31fc05985d", 0, <item:mysticalagradditions:creative_essence>, [
	[<item:extendedcrafting:luminessence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:extendedcrafting:luminessence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:mysticalagriculture:fire_essence>, <item:mysticalagriculture:air_essence>, <item:mysticalagriculture:air_essence>, <item:mysticalagradditions:insanium_essence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:mysticalagriculture:fire_essence>, <item:evilcraft:vengeance_essence_materialized>, <item:mysticalagriculture:earth_essence>, <item:mysticalagradditions:insanium_essence>], 
	[<item:mysticalagradditions:insanium_essence>, <item:mysticalagriculture:water_essence>, <item:mysticalagriculture:water_essence>, <item:mysticalagriculture:earth_essence>, <item:mysticalagradditions:insanium_essence>], 
	[<item:extendedcrafting:luminessence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:mysticalagradditions:insanium_essence>, <item:extendedcrafting:luminessence>]
]);

mods.extendedcrafting.TableCrafting.addShaped("d299381f-1eb0-4e8a-bf0c-142c1a006f61", 0, <item:easy_mob_farm:capture_net>, [
	[<item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:easy_mob_farm:fishing_bowl>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_bowl>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_bowl>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:easy_mob_farm:collar_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:collar_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:collar_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>], 
	[<item:easy_mob_farm:insect_net>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_net_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:crystaltine_ingot>, <item:easy_mob_farm:urn_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:witch_bottle>.withTag({Damage: 0 as int})], 
	[<item:easy_mob_farm:insect_net>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_net_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:easy_mob_farm:urn_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:witch_bottle>.withTag({Damage: 0 as int})], 
	[<item:easy_mob_farm:insect_net>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_net_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:crystaltine_ingot>, <item:easy_mob_farm:urn_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:witch_bottle>.withTag({Damage: 0 as int})], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:easy_mob_farm:catch_cage_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:easy_mob_farm:catch_cage>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>]
]);

mods.extendedcrafting.TableCrafting.addShaped("73d4dcce-86e7-437f-8c6d-020c143410c9", 0, <item:easy_mob_farm:creative_mob_catcher>, [
	[<item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:easy_mob_farm:fishing_bowl>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_bowl>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_bowl>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:easy_mob_farm:collar_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:collar_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:collar_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>], 
	[<item:easy_mob_farm:insect_net>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_net_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:crystaltine_ingot>, <item:easy_mob_farm:urn_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:witch_bottle>.withTag({Damage: 0 as int})], 
	[<item:easy_mob_farm:insect_net>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_net_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:easy_mob_farm:urn_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:witch_bottle>.withTag({Damage: 0 as int})], 
	[<item:easy_mob_farm:insect_net>.withTag({Damage: 0 as int}), <item:easy_mob_farm:fishing_net_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:crystaltine_ingot>, <item:easy_mob_farm:urn_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:witch_bottle>.withTag({Damage: 0 as int})], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:easy_mob_farm:catch_cage_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage_small>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage_small>.withTag({Damage: 0 as int}), <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:easy_mob_farm:catch_cage>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage>.withTag({Damage: 0 as int}), <item:easy_mob_farm:catch_cage>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>]
]);

mods.extendedcrafting.TableCrafting.addShaped("d31b332c-d6e3-40dc-89d5-a24cf876126f", 0, <item:easy_mob_farm:creative_mob_farm>, [
	[<item:darkutils:filter_player>, <item:darkutils:filter_player>, <item:mob_grinding_utils:delightful_dirt>, <item:mob_grinding_utils:delightful_dirt>, <item:mob_grinding_utils:delightful_dirt>, <item:darkutils:filter_player>, <item:darkutils:filter_player>], 
	[<item:darkutils:filter_player>, <item:easy_mob_farm:capture_net>.withTag({Damage: 0 as int}), <item:mob_grinding_utils:saw>, <item:easy_mob_farm:swamp_farm>, <item:mob_grinding_utils:saw>, <item:easy_mob_farm:creative_mob_catcher>.withTag({Damage: 0 as int}), <item:darkutils:filter_player>], 
	[<item:mob_grinding_utils:dreadful_dirt>, <item:mob_grinding_utils:saw>, <item:mob_grinding_utils:saw>, <item:extendedcrafting:crystaltine_ingot>, <item:mob_grinding_utils:saw>, <item:mob_grinding_utils:saw>, <item:mob_grinding_utils:dreadful_dirt>], 
	[<item:extendedcrafting:flux_star>, <item:easy_mob_farm:jungle_farm>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:easy_mob_farm:desert_farm>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:easy_mob_farm:nether_fortress_farm>, <item:extendedcrafting:ender_star>], 
	[<item:mob_grinding_utils:dreadful_dirt>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_ingot>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mob_grinding_utils:dreadful_dirt>], 
	[<item:darkutils:filter_player>, <item:easy_mob_farm:creative_mob_catcher>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:easy_mob_farm:ocean_farm>, <item:mysticalagradditions:creative_essence>, <item:easy_mob_farm:capture_net>.withTag({Damage: 0 as int}), <item:darkutils:filter_player>], 
	[<item:darkutils:filter_player>, <item:darkutils:filter_player>, <item:mob_grinding_utils:fan>, <item:mob_grinding_utils:fan>, <item:mob_grinding_utils:fan>, <item:darkutils:filter_player>, <item:darkutils:filter_player>]
]);

mods.extendedcrafting.TableCrafting.addShaped("e5a452ed-e0a6-48ce-960f-3104d5a28eac", 0, <item:mysticalagriculture:creative_soulium_dagger>, [
	[<item:mysticalagriculture:passive_soulium_dagger>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:aquaculture:neptunium_sword>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:twilightforest:fiery_sword>.withTag({Damage: 0 as int})], 
	[<item:extendedcrafting:flux_star>, <item:mysticalagriculture:passive_soulium_dagger>.withTag({Damage: 0 as int}), <item:mysticalagriculture:end_essence>, <item:mysticalagriculture:fertilized_essence>, <item:mysticalagriculture:fertilized_essence>, <item:mysticalagriculture:fertilized_essence>, <item:mysticalagriculture:end_essence>, <item:mysticalagriculture:dragon_egg_essence>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:mysticalagriculture:end_essence>, <item:mysticalagriculture:passive_soulium_dagger>.withTag({Damage: 0 as int}), <item:evilcraft:blood_infusion_core>, <item:evilcraft:blood_infusion_core>, <item:evilcraft:blood_infusion_core>, <item:mysticalagriculture:awakened_supremium_sword>, <item:mysticalagriculture:end_essence>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:mysticalagriculture:fertilized_essence>, <item:hexerei:blood_bottle>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:hexerei:blood_bottle>, <item:mysticalagriculture:fertilized_essence>, <item:extendedcrafting:flux_star>], 
	[<item:minecraft:netherite_sword>.withTag({Damage: 0 as int}), <item:mysticalagriculture:fertilized_essence>, <item:botania:brew_flask>.withTag({brewKey: "botania:bloodthirst"}), <item:extendedcrafting:crystaltine_ingot>, <item:easy_mob_farm:creative_mob_farm>, <item:extendedcrafting:crystaltine_ingot>, <item:botania:brew_flask>.withTag({brewKey: "botania:bloodthirst"}), <item:mysticalagriculture:fertilized_essence>, <item:evilcraft:vein_sword>.withTag({Damage: 0 as int, Enchantments: [{lvl: 2 as short, id: "minecraft:looting"}]})], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagriculture:fertilized_essence>, <item:hexerei:blood_bottle>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:hexerei:blood_bottle>, <item:mysticalagriculture:fertilized_essence>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagriculture:end_essence>, <item:mysticalagriculture:awakened_supremium_sword>, <item:evilcraft:blood_infusion_core>, <item:evilcraft:blood_infusion_core>, <item:evilcraft:blood_infusion_core>, <item:mysticalagriculture:hostile_soulium_dagger>.withTag({Damage: 0 as int}), <item:mysticalagriculture:end_essence>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagriculture:dragon_egg_essence>, <item:mysticalagriculture:end_essence>, <item:mysticalagriculture:fertilized_essence>, <item:mysticalagriculture:fertilized_essence>, <item:mysticalagriculture:fertilized_essence>, <item:mysticalagriculture:end_essence>, <item:mysticalagriculture:hostile_soulium_dagger>.withTag({Damage: 0 as int}), <item:extendedcrafting:ender_star>], 
	[<item:twilightforest:fiery_sword>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:blue_skies:different_sword>.withTag({Damage: 0 as int}), <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagriculture:hostile_soulium_dagger>.withTag({Damage: 0 as int})]
]);

mods.extendedcrafting.TableCrafting.addShaped("57ac62f9-bb7f-4cb0-a640-0896c8932fc4", 0, <item:hexerei:creative_waxing_kit>, [
	[<item:hexerei:waxing_kit>, <item:hexerei:waxing_kit>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:hexerei:waxing_kit>, <item:hexerei:waxing_kit>], 
	[<item:hexerei:waxing_kit>, <item:hexerei:wax_blend>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:hexerei:cloth>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:hexerei:wax_blend>, <item:hexerei:waxing_kit>], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ender_star>, <item:hexerei:wax_blend>, <item:evilcraft:blood_waxed_coal_block>, <item:evilcraft:blood_waxed_coal_block>, <item:evilcraft:blood_waxed_coal_block>, <item:hexerei:wax_blend>, <item:extendedcrafting:ender_star>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_ingot>, <item:hexerei:wax_blend>, <item:evilcraft:blood_waxed_coal_block>, <item:easy_mob_farm:creative_mob_farm>, <item:evilcraft:blood_waxed_coal_block>, <item:hexerei:wax_blend>, <item:extendedcrafting:crystaltine_ingot>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ender_star>, <item:hexerei:wax_blend>, <item:evilcraft:blood_waxed_coal_block>, <item:evilcraft:blood_waxed_coal_block>, <item:evilcraft:blood_waxed_coal_block>, <item:hexerei:wax_blend>, <item:extendedcrafting:ender_star>, <item:mysticalagradditions:creative_essence>], 
	[<item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:hexerei:wax_blend>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>], 
	[<item:hexerei:waxing_kit>, <item:hexerei:wax_blend>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_ingot>, <item:hexerei:cloth>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:hexerei:wax_blend>, <item:hexerei:waxing_kit>], 
	[<item:hexerei:waxing_kit>, <item:hexerei:waxing_kit>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:hexerei:waxing_kit>, <item:hexerei:waxing_kit>]
]);

mods.extendedcrafting.TableCrafting.addShaped("02791674-61e3-46d3-bbc5-1c0bed0bde49", 0, <item:mekanism:creative_bin>, [
	[<item:mekanism:ultimate_bin>, <item:mekanism:ultimate_bin>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:mekanism:ultimate_bin>, <item:mekanism:ultimate_bin>], 
	[<item:mekanism:ultimate_bin>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mekanism:ultimate_bin>], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_ingot>, <item:hexerei:blood_bottle>, <item:hexerei:blood_bottle>, <item:hexerei:blood_bottle>, <item:extendedcrafting:crystaltine_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_ingot>, <item:hexerei:blood_bottle>, <item:hexerei:creative_waxing_kit>, <item:hexerei:blood_bottle>, <item:extendedcrafting:crystaltine_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:crystaltine_ingot>, <item:hexerei:blood_bottle>, <item:hexerei:blood_bottle>, <item:hexerei:blood_bottle>, <item:extendedcrafting:crystaltine_ingot>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ender_star>], 
	[<item:extendedcrafting:ender_star>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:ender_star>], 
	[<item:mekanism:ultimate_bin>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mekanism:ultimate_bin>], 
	[<item:mekanism:ultimate_bin>, <item:mekanism:ultimate_bin>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:mekanism:ultimate_bin>, <item:mekanism:ultimate_bin>]
]);

mods.extendedcrafting.TableCrafting.addShaped("590d0ada-1086-43b1-9c07-404af5193c8b", 0, <item:botania:infrangible_platform>, [
	[<item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:mekanism:block_refined_obsidian>, <item:mysticalagriculture:refined_obsidian_seeds>, <item:mysticalagriculture:obsidian_seeds>, <item:fluxnetworks:flux_block>, <item:twilightforest:giant_obsidian>, <item:fluxnetworks:flux_block>, <item:mysticalagriculture:obsidian_seeds>, <item:mysticalagriculture:refined_obsidian_seeds>, <item:mekanism:block_refined_obsidian>], 
	[<item:mekanism:block_refined_obsidian>, <item:mysticalagriculture:obsidian_seeds>, <item:extendedcrafting:crystaltine_component>, <item:mekanism:enriched_refined_obsidian>, <item:extendedcrafting:flux_star>, <item:mekanism:enriched_refined_obsidian>, <item:extendedcrafting:crystaltine_component>, <item:mysticalagriculture:obsidian_seeds>, <item:mekanism:block_refined_obsidian>], 
	[<item:mekanism:block_refined_obsidian>, <item:fluxnetworks:flux_block>, <item:mekanism:enriched_refined_obsidian>, <item:minecraft:crying_obsidian>, <item:mysticalagriculture:creative_soulium_dagger>, <item:minecraft:crying_obsidian>, <item:mekanism:enriched_refined_obsidian>, <item:fluxnetworks:flux_block>, <item:mekanism:block_refined_obsidian>], 
	[<item:mekanism:block_refined_obsidian>, <item:twilightforest:giant_obsidian>, <item:extendedcrafting:flux_star>, <item:hexerei:creative_waxing_kit>, <item:extendedcrafting:the_ultimate_ingot>, <item:hexerei:creative_waxing_kit>, <item:extendedcrafting:ender_star>, <item:twilightforest:giant_obsidian>, <item:mekanism:block_refined_obsidian>], 
	[<item:mekanism:block_refined_obsidian>, <item:fluxnetworks:flux_block>, <item:mekanism:enriched_refined_obsidian>, <item:minecraft:crying_obsidian>, <item:mysticalagriculture:creative_soulium_dagger>, <item:minecraft:crying_obsidian>, <item:mekanism:enriched_refined_obsidian>, <item:fluxnetworks:flux_block>, <item:mekanism:block_refined_obsidian>], 
	[<item:mekanism:block_refined_obsidian>, <item:mysticalagriculture:obsidian_seeds>, <item:extendedcrafting:crystaltine_component>, <item:mekanism:enriched_refined_obsidian>, <item:extendedcrafting:ender_star>, <item:mekanism:enriched_refined_obsidian>, <item:extendedcrafting:crystaltine_component>, <item:mysticalagriculture:obsidian_seeds>, <item:mekanism:block_refined_obsidian>], 
	[<item:mekanism:block_refined_obsidian>, <item:mysticalagriculture:refined_obsidian_seeds>, <item:mysticalagriculture:obsidian_seeds>, <item:fluxnetworks:flux_block>, <item:twilightforest:giant_obsidian>, <item:fluxnetworks:flux_block>, <item:mysticalagriculture:obsidian_seeds>, <item:mysticalagriculture:refined_obsidian_seeds>, <item:mekanism:block_refined_obsidian>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:mysticalagradditions:creative_essence>, <item:extendedcrafting:the_ultimate_ingot>]
]);

mods.extendedcrafting.TableCrafting.addShaped("58b383b1-14d1-41e2-98e0-532e78d7ddfd", 0, <item:ae2:creative_energy_cell>, [
	[<item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_component>, <item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>], 
	[<item:ae2:dense_energy_cell>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:ae2:dense_energy_cell>], 
	[<item:extendedcrafting:crystaltine_component>, <item:botania:infrangible_platform>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:botania:infrangible_platform>, <item:extendedcrafting:crystaltine_component>], 
	[<item:ae2:dense_energy_cell>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:ae2:dense_energy_cell>], 
	[<item:ae2:dense_energy_cell>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:appmek:portable_chemical_storage_cell_256k>, <item:ae2:portable_fluid_cell_256k>, <item:ae2:portable_item_cell_256k>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:ae2:dense_energy_cell>], 
	[<item:ae2:dense_energy_cell>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:ae2:dense_energy_cell>], 
	[<item:extendedcrafting:crystaltine_component>, <item:botania:infrangible_platform>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:botania:infrangible_platform>, <item:extendedcrafting:crystaltine_component>], 
	[<item:ae2:dense_energy_cell>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:ae2:dense_energy_cell>], 
	[<item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_component>, <item:ae2:dense_energy_cell>, <item:ae2:dense_energy_cell>]
]);

mods.extendedcrafting.TableCrafting.addShaped("539b57e3-a909-4813-b24f-5b00028149c9", 0, <item:integrateddynamics:energy_battery_creative>, [
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:coal_generator>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})], 
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:extendedcrafting:enhanced_redstone_catalyst>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:mekanismgenerators:heat_generator>, <item:extendedcrafting:crystaltine_component>, <item:mekanismgenerators:heat_generator>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:extendedcrafting:enhanced_redstone_catalyst>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})], 
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagriculture:gaia_spirit_essence>, <item:ultimatefurnaces_bfr:ultimate_forge>, <item:mysticalagriculture:gaia_spirit_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:crystaltine_component>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})], 
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:extendedcrafting:crystaltine_component>, <item:mysticalagriculture:awakened_supremium_furnace>, <item:mysticalagriculture:gaia_spirit_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagriculture:gaia_spirit_essence>, <item:mysticalagriculture:awakened_supremium_furnace>, <item:extendedcrafting:crystaltine_component>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})], 
	[<item:integrateddynamics:coal_generator>, <item:extendedcrafting:crystaltine_component>, <item:mekanismgenerators:advanced_solar_generator>, <item:mekanismgenerators:wind_generator>, <item:ae2:creative_energy_cell>, <item:mekanismgenerators:wind_generator>, <item:mekanismgenerators:advanced_solar_generator>, <item:extendedcrafting:crystaltine_component>, <item:integrateddynamics:coal_generator>], 
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:extendedcrafting:crystaltine_component>, <item:mysticalagriculture:awakened_supremium_furnace>, <item:mysticalagriculture:gaia_spirit_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagriculture:gaia_spirit_essence>, <item:mysticalagriculture:awakened_supremium_furnace>, <item:extendedcrafting:crystaltine_component>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})], 
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:the_ultimate_ingot>, <item:mysticalagriculture:gaia_spirit_essence>, <item:ultimatefurnaces_bfr:ultimate_forge>, <item:mysticalagriculture:gaia_spirit_essence>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:crystaltine_component>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})], 
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:mekanismgenerators:heat_generator>, <item:extendedcrafting:crystaltine_component>, <item:mekanismgenerators:heat_generator>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})], 
	[<item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:coal_generator>, <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int}), <item:integrateddynamics:energy_battery>.withTag({energy: 0 as int})]
]);

mods.extendedcrafting.TableCrafting.addShaped("ffeda86e-627a-4689-bcb0-ff74a23e6624", 0, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4, side3: 4, side5: 4, side0: 4, side2: 4, side1: 4}}}}), [
	[<item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000"}]}}), <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_tier_installer>, <item:mekanism:pellet_antimatter>, <item:mekanism:ultimate_energy_cube>, <item:mekanism:pellet_antimatter>, <item:mekanism:ultimate_tier_installer>, <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000"}]}})], 
	[<item:mekanism:ultimate_control_circuit>, <item:integrateddynamics:energy_battery_creative>, <item:mekanism:ultimate_tier_installer>, <item:fluxnetworks:flux_block>, <item:fluxnetworks:flux_block>, <item:fluxnetworks:flux_block>, <item:mekanism:ultimate_tier_installer>, <item:integrateddynamics:energy_battery_creative>, <item:mekanism:ultimate_control_circuit>], 
	[<item:mekanism:ultimate_tier_installer>, <item:mekanism:ultimate_tier_installer>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:mekanism:ultimate_tier_installer>, <item:mekanism:ultimate_tier_installer>], 
	[<item:mekanism:pellet_antimatter>, <item:fluxnetworks:flux_block>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_component>, <item:fluxnetworks:flux_block>, <item:mekanism:pellet_antimatter>], 
	[<item:mekanism:ultimate_energy_cube>, <item:fluxnetworks:flux_block>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:crystaltine_ingot>, <item:integrateddynamics:energy_battery_creative>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:the_ultimate_component>, <item:fluxnetworks:flux_block>, <item:mekanism:ultimate_energy_cube>], 
	[<item:mekanism:pellet_antimatter>, <item:fluxnetworks:flux_block>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_component>, <item:fluxnetworks:flux_block>, <item:mekanism:pellet_antimatter>], 
	[<item:mekanism:ultimate_tier_installer>, <item:mekanism:ultimate_tier_installer>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:mekanism:ultimate_tier_installer>, <item:mekanism:ultimate_tier_installer>], 
	[<item:mekanism:ultimate_control_circuit>, <item:integrateddynamics:energy_battery_creative>, <item:mekanism:ultimate_tier_installer>, <item:fluxnetworks:flux_block>, <item:fluxnetworks:flux_block>, <item:fluxnetworks:flux_block>, <item:mekanism:ultimate_tier_installer>, <item:integrateddynamics:energy_battery_creative>, <item:mekanism:ultimate_control_circuit>], 
	[<item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000"}]}}), <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_tier_installer>, <item:mekanism:pellet_antimatter>, <item:mekanism:ultimate_energy_cube>, <item:mekanism:pellet_antimatter>, <item:mekanism:ultimate_tier_installer>, <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000"}]}})]
]);

mods.extendedcrafting.TableCrafting.addShaped("7c476dca-da41-4866-8e89-d6f926b774ab", 0, <item:refinedstorage:creative_controller>, [
	[<item:refinedstorage:controller>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:refinedstorage:controller>], 
	[<item:extendedcrafting:enhanced_redstone_catalyst>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_redstone_catalyst>], 
	[<item:extendedcrafting:enhanced_redstone_catalyst>, <item:botania:infrangible_platform>, <item:refinedstorage:controller>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:refinedstorage:controller>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_redstone_catalyst>], 
	[<item:mysticalagradditions:creative_essence>, <item:botania:infrangible_platform>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:the_ultimate_component>, <item:botania:infrangible_platform>, <item:mysticalagradditions:creative_essence>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:botania:infrangible_platform>, <item:extendedcrafting:the_ultimate_component>, <item:ae2:creative_energy_cell>, <item:extendedcrafting:the_ultimate_ingot>, <item:ae2:creative_energy_cell>, <item:extendedcrafting:the_ultimate_component>, <item:botania:infrangible_platform>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:mysticalagradditions:creative_essence>, <item:botania:infrangible_platform>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:the_ultimate_component>, <item:botania:infrangible_platform>, <item:mysticalagradditions:creative_essence>], 
	[<item:extendedcrafting:enhanced_redstone_catalyst>, <item:botania:infrangible_platform>, <item:refinedstorage:controller>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:refinedstorage:controller>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_redstone_catalyst>], 
	[<item:extendedcrafting:enhanced_redstone_catalyst>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:enhanced_ender_catalyst>, <item:botania:infrangible_platform>, <item:extendedcrafting:enhanced_redstone_catalyst>], 
	[<item:refinedstorage:controller>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:botania:infrangible_platform>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:refinedstorage:controller>]
]);

mods.extendedcrafting.TableCrafting.addShaped("1a663db8-0154-4def-a175-21fd538b8e3e", 0, <item:refinedstorage:creative_storage_disk>, [
	[<item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<tag:items:refinedstorage:parts/items/16384k>, <tag:items:refinedstorage:parts/items/16384k>, <tag:items:refinedstorage:parts/items/16384k>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <item:refinedstorage:creative_controller>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <tag:items:refinedstorage:parts/items/16384k>, <tag:items:refinedstorage:parts/items/16384k>, <tag:items:refinedstorage:parts/items/16384k>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>]
]);

mods.extendedcrafting.TableCrafting.addShaped("16932bdb-202e-4da4-9e6d-bc60d404ac27", 0, <item:refinedstorage:creative_fluid_storage_disk>, [
	[<item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<tag:items:refinedstorage:parts/fluids/1048576k>, <tag:items:refinedstorage:parts/fluids/1048576k>, <tag:items:refinedstorage:parts/fluids/1048576k>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <item:refinedstorage:creative_controller>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <tag:items:refinedstorage:parts/fluids/1048576k>, <tag:items:refinedstorage:parts/fluids/1048576k>, <tag:items:refinedstorage:parts/fluids/1048576k>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999"}], componentConfig: {config0: {side4: 4 as int, side3: 4 as int, side5: 4 as int, side0: 4 as int, side2: 4 as int, side1: 4 as int}}}}), <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:crystaltine_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_ingot>], 
	[<item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>]
]);

mods.extendedcrafting.EnderCrafting.addShaped("94a0ee90-d9dd-42e2-954d-b42ebba8b09c", <item:refinedstorage:creative_portable_grid>, [
	[<item:extendedcrafting:the_ultimate_component>, <item:refinedstorage:creative_storage_disk>, <item:extendedcrafting:the_ultimate_component>], 
	[<item:refinedstorage:creative_fluid_storage_disk>, <item:extendedcrafting:the_ultimate_component>, <item:refinedstorage:creative_storage_disk>], 
	[<item:extendedcrafting:the_ultimate_component>, <item:refinedstorage:creative_fluid_storage_disk>, <item:extendedcrafting:the_ultimate_component>]
]);

mods.extendedcrafting.FluxCrafting.addShaped("2d998ac2-b6b0-4779-a039-8f8f49a23576", <item:refinedstorage:creative_storage_block>, [
	[<item:extrastorage:block_16384k>, <item:extrastorage:block_16384k>, <item:extrastorage:block_16384k>], 
	[<item:extrastorage:block_16384k>, <item:refinedstorage:creative_storage_disk>, <item:extrastorage:block_16384k>], 
	[<item:extrastorage:block_16384k>, <item:extrastorage:block_16384k>, <item:extrastorage:block_16384k>]
], 100000, 400);

mods.extendedcrafting.FluxCrafting.addShaped("0301a486-69f3-45cd-b857-38731e1d4895", <item:refinedstorage:creative_fluid_storage_block>, [
	[<item:extrastorage:block_1048576k_fluid>, <item:extrastorage:block_1048576k_fluid>, <item:extrastorage:block_1048576k_fluid>], 
	[<item:extrastorage:block_1048576k_fluid>, <item:refinedstorage:creative_fluid_storage_disk>, <item:extrastorage:block_1048576k_fluid>], 
	[<item:extrastorage:block_1048576k_fluid>, <item:extrastorage:block_1048576k_fluid>, <item:extrastorage:block_1048576k_fluid>]
], 100000, 400);

mods.extendedcrafting.EnderCrafting.addShaped("138e791d-159d-446f-9ac7-74fdefdbda60", <item:refinedstorage:creative_wireless_grid>, [
	[<item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>], 
	[<item:refinedstorage:creative_storage_block>, <item:refinedstorage:wireless_grid>, <item:refinedstorage:creative_storage_block>], 
	[<item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>]
]);

mods.extendedcrafting.FluxCrafting.addShaped("50a6ea1b-e042-4af6-9239-b2972eb95508", <item:refinedstorage:creative_wireless_fluid_grid>, [
	[<item:refinedstorage:creative_fluid_storage_block>, <item:refinedstorage:creative_fluid_storage_block>, <item:refinedstorage:creative_fluid_storage_block>], 
	[<item:refinedstorage:creative_fluid_storage_block>, <item:refinedstorage:wireless_fluid_grid>, <item:refinedstorage:creative_fluid_storage_block>], 
	[<item:refinedstorage:creative_fluid_storage_block>, <item:refinedstorage:creative_fluid_storage_block>, <item:refinedstorage:creative_fluid_storage_block>]
], 100000, 400);

mods.extendedcrafting.FluxCrafting.addShaped("b5ecef60-8a0a-43de-a8a0-c86645150c9c", <item:refinedstorage:creative_wireless_crafting_monitor>, [
	[<item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>], 
	[<item:refinedstorage:creative_storage_block>, <item:refinedstorage:wireless_crafting_monitor>, <item:refinedstorage:creative_storage_block>], 
	[<item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>, <item:refinedstorage:creative_storage_block>]
], 100000, 400);

mods.extendedcrafting.FluxCrafting.addShaped("117c3e7a-b721-4813-907b-e153681ce546", <item:universalgrid:creative_wireless_universal_grid>, [
	[<item:minecraft:air>, <item:refinedstorage:creative_wireless_grid>, <item:minecraft:air>], 
	[<item:universalgrid:wireless_universal_grid>.withTag({gridType: 0 as int}), <item:refinedstorage:creative_wireless_fluid_grid>, <item:universalgrid:wireless_universal_grid>], 
	[<item:minecraft:air>, <item:refinedstorage:creative_wireless_crafting_monitor>, <item:minecraft:air>]
], 100000, 400);

mods.extendedcrafting.FluxCrafting.addShaped("dd8df964-383d-4bae-8be0-4412c42b8d51", <item:refinedstorageaddons:creative_wireless_crafting_grid>, [
	[<item:refinedstorageaddons:wireless_crafting_grid>, <item:extendedcrafting:flux_star>, <item:refinedstorageaddons:wireless_crafting_grid>], 
	[<item:extendedcrafting:flux_star>, <item:refinedstorageaddons:wireless_crafting_grid>, <item:extendedcrafting:flux_star>], 
	[<item:refinedstorageaddons:wireless_crafting_grid>, <item:extendedcrafting:flux_star>, <item:refinedstorageaddons:wireless_crafting_grid>]
], 100000, 400);

mods.extendedcrafting.FluxCrafting.addShaped("c78f61b7-2e99-491b-af73-27be5b109be8", <item:rebornstorage:creative_super_wireless_crafting_grid>, [
	[<item:minecraft:air>, <item:extendedcrafting:ultimate_singularity>, <item:minecraft:air>], 
	[<item:extendedcrafting:flux_star>, <item:rebornstorage:super_wireless_crafting_grid>, <item:extendedcrafting:flux_star>], 
	[<item:minecraft:air>, <item:extendedcrafting:ultimate_singularity>, <item:minecraft:air>]
], 100000, 400);

mods.extendedcrafting.FluxCrafting.addShaped("dfa84de3-122f-4c11-9ec7-b1b7931393e8", <item:botania:lens_storm>, [
	[<item:refinedstorage:creative_storage_disk>, <item:rebornstorage:creative_super_wireless_crafting_grid>, <item:refinedstorage:creative_fluid_storage_disk>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:universalgrid:creative_wireless_universal_grid>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:refinedstorage:creative_storage_disk>, <item:refinedstorageaddons:creative_wireless_crafting_grid>, <item:refinedstorage:creative_fluid_storage_disk>]
], 100000, 400);

mods.extendedcrafting.TableCrafting.addShaped("092de926-9465-44bb-abaa-356673ee0b70", 0, <item:botania:mana_tablet>.withTag({mana: 500000, creative: 1}), [
	[<item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:lens_storm>, <item:botania:jiyuulia>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:tangleberrie_chibi>, <item:botania:lens_storm>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:mana_tablet>.withTag({mana: 500000 as int})], 
	[<item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:hyacidus>, <item:extendedcrafting:the_ultimate_component>, <item:botania:heisei_dream>, <item:botania:marimorphosis>, <item:botania:tigerseye>, <item:extendedcrafting:the_ultimate_component>, <item:botania:vinculotus>, <item:botania:mana_tablet>.withTag({mana: 500000 as int})], 
	[<item:botania:lens_storm>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:crystaltine_component>, <item:botania:orechid>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:fallen_kanade>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:the_ultimate_component>, <item:botania:lens_storm>], 
	[<item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>], 
	[<item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:labellia>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:extendedcrafting:the_ultimate_component>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:extendedcrafting:the_ultimate_component>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:orechid_ignem>, <item:botania:mana_tablet>.withTag({mana: 500000 as int})], 
	[<item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>], 
	[<item:botania:lens_storm>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:crystaltine_component>, <item:botania:agricarnation>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:exoflame>, <item:extendedcrafting:crystaltine_component>, <item:extendedcrafting:the_ultimate_component>, <item:botania:lens_storm>], 
	[<item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:pollidisiac>, <item:extendedcrafting:the_ultimate_component>, <item:botania:jaded_amaranthus>, <item:botania:solegnolia>, <item:botania:bergamute>, <item:extendedcrafting:the_ultimate_component>, <item:botania:spectranthemum>, <item:botania:mana_tablet>.withTag({mana: 500000 as int})], 
	[<item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:lens_storm>, <item:botania:rannuncarpus>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:loonium>, <item:botania:lens_storm>, <item:botania:mana_tablet>.withTag({mana: 500000 as int}), <item:botania:mana_tablet>.withTag({mana: 500000 as int})]
]);

mods.extendedcrafting.TableCrafting.addShaped("cde00e6c-b7f0-4654-9acb-cebd2d859951", 0, <item:botania:creative_pool>, [
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>], 
	[<item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>], 
	[<item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:mana_tablet>.withTag({mana: 500000 as int, creative: 1 as byte}), <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>], 
	[<item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>], 
	[<item:botania:fabulous_pool>, <item:extendedcrafting:ultimate_singularity>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:botania:fabulous_pool>, <item:extendedcrafting:ultimate_singularity>, <item:botania:fabulous_pool>]
]);

mods.extendedcrafting.TableCrafting.addShaped("e759de50-193c-4e54-b8fd-ba4b5a165ac0", 0, <item:botania:corporea_spark_creative>, [
	[<item:botania:creative_pool>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:botania:creative_pool>], 
	[<item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ultimate_singularity>, <item:botania:spark>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ultimate_singularity>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:ender_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>], 
	[<item:extendedcrafting:flux_star>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:the_ultimate_component>, <item:extendedcrafting:flux_star>], 
	[<item:botania:creative_pool>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:extendedcrafting:flux_star>, <item:botania:creative_pool>]
]);